<h1>Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Video-&quot;What-is-TensorFlow&quot;" data-toc-modified-id="Video-&quot;What-is-TensorFlow&quot;-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Video "What is TensorFlow"</a></span></li><li><span><a href="#Video-&quot;Our-first-model-in-TensorFlow&quot;" data-toc-modified-id="Video-&quot;Our-first-model-in-TensorFlow&quot;-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Video "Our first model in TensorFlow"</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#Simple-optimization-(with-simple-prints)" data-toc-modified-id="Simple-optimization-(with-simple-prints)-2.0.1"><span class="toc-item-num">2.0.1&nbsp;&nbsp;</span>Simple optimization (with simple prints)</a></span></li><li><span><a href="#Simple-optimization-(with-tf.Print)" data-toc-modified-id="Simple-optimization-(with-tf.Print)-2.0.2"><span class="toc-item-num">2.0.2&nbsp;&nbsp;</span>Simple optimization (with tf.Print)</a></span></li><li><span><a href="#Simple-optimization-(with-TensorBoard-logging)" data-toc-modified-id="Simple-optimization-(with-TensorBoard-logging)-2.0.3"><span class="toc-item-num">2.0.3&nbsp;&nbsp;</span>Simple optimization (with TensorBoard logging)</a></span></li><li><span><a href="#Training-a-linear-model" data-toc-modified-id="Training-a-linear-model-2.0.4"><span class="toc-item-num">2.0.4&nbsp;&nbsp;</span>Training a linear model</a></span></li></ul></li></ul></li></ul></div>

In [2]:
# set tf 1.x for colab
%tensorflow_version 1.x

TensorFlow 1.x selected.


# Video "What is TensorFlow"

In [4]:
%config IPCompleter.greedy=True

In [5]:
import tensorflow as tf
import numpy as np
print(tf.__version__)

1.15.2


In [6]:
tf.reset_default_graph()
a = tf.placeholder(np.float32, (2, 2))
b = tf.Variable(tf.ones((2, 2)))
c = a @ b

In [7]:
print(c)

Tensor("matmul:0", shape=(2, 2), dtype=float32)


In [8]:
s = tf.InteractiveSession()

In [9]:
s.run(tf.global_variables_initializer())
s.run(c, feed_dict={a: np.ones((2, 2))})

array([[2., 2.],
       [2., 2.]], dtype=float32)

In [10]:
s.close()

# Video "Our first model in TensorFlow"

### Simple optimization (with simple prints)

In [11]:
tf.reset_default_graph()
x = tf.get_variable("x", shape=(), dtype=tf.float32, trainable=True)
f = x ** 2

In [12]:
optimizer = tf.train.GradientDescentOptimizer(0.1, name = "GD")
step = optimizer.minimize(f, var_list=[x])

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [13]:
tf.trainable_variables()

[<tf.Variable 'x:0' shape=() dtype=float32_ref>]

In [14]:
with tf.Session() as s:  # in this way session will be closed automatically
    s.run(tf.global_variables_initializer())
    for i in range(10):
        _, curr_x, curr_f = s.run([step, x, f])
        print(curr_x, curr_f)

-0.7121898 0.7925223
-0.56975186 0.5072143
-0.4558015 0.32461718
-0.3646412 0.207755
-0.29171294 0.1329632
-0.23337035 0.08509644
-0.18669628 0.05446172
-0.14935702 0.0348555
-0.11948562 0.022307519
-0.09558849 0.014276813


### Simple optimization (with tf.Print)

In [15]:
tf.reset_default_graph()
x = tf.get_variable("x", shape=(), dtype=tf.float32)
f = x ** 2
f = tf.Print(f, [x, f], "x, f:")

Instructions for updating:
Use tf.print instead of tf.Print. Note that tf.print returns a no-output operator that directly prints the output. Outside of defuns or eager mode, this operator will not be executed unless it is directly specified in session.run or used as a control dependency for other operators. This is only a concern in graph mode. Below is an example of how to ensure tf.print executes in graph mode:



In [16]:
optimizer = tf.train.GradientDescentOptimizer(0.1)
step = optimizer.minimize(f)

In [17]:
with tf.Session() as s:
    s.run(tf.global_variables_initializer())
    for i in range(10):
        s.run([step, f])

In [ ]:
# Prints to jupyter server stdout (not available in Coursera Notebooks):
# 2018-07-21 18:01:27.308270: I tensorflow/core/kernels/logging_ops.cc:79] x, f:[-1.0670249][1.1385423]
# 2018-07-21 18:01:27.308809: I tensorflow/core/kernels/logging_ops.cc:79] x, f:[-0.85361993][0.72866696]
# 2018-07-21 18:01:27.309116: I tensorflow/core/kernels/logging_ops.cc:79] x, f:[-0.68289596][0.46634689]
# 2018-07-21 18:01:27.309388: I tensorflow/core/kernels/logging_ops.cc:79] x, f:[-0.54631674][0.29846197]
# 2018-07-21 18:01:27.309678: I tensorflow/core/kernels/logging_ops.cc:79] x, f:[-0.43705338][0.19101566]
# 2018-07-21 18:01:27.309889: I tensorflow/core/kernels/logging_ops.cc:79] x, f:[-0.34964269][0.12225001]
# 2018-07-21 18:01:27.310213: I tensorflow/core/kernels/logging_ops.cc:79] x, f:[-0.27971417][0.078240015]
# 2018-07-21 18:01:27.310475: I tensorflow/core/kernels/logging_ops.cc:79] x, f:[-0.22377133][0.050073609]
# 2018-07-21 18:01:27.310751: I tensorflow/core/kernels/logging_ops.cc:79] x, f:[-0.17901707][0.032047112]
# 2018-07-21 18:01:27.310963: I tensorflow/core/kernels/logging_ops.cc:79] x, f:[-0.14321366][0.020510152]

### Simple optimization (with TensorBoard logging)

In [18]:
tf.reset_default_graph()
x = tf.get_variable("x", shape=(), dtype=tf.float32)
f = x ** 2

In [19]:
optimizer = tf.train.GradientDescentOptimizer(0.1)
step = optimizer.minimize(f)

In [20]:
tf.summary.scalar('curr_x', x)
tf.summary.scalar('curr_f', f)
summaries = tf.summary.merge_all()

In [21]:
s = tf.InteractiveSession()
summary_writer = tf.summary.FileWriter("logs/1", s.graph)
s.run(tf.global_variables_initializer())
for i in range(10):
    _, curr_summaries = s.run([step, summaries])
    summary_writer.add_summary(curr_summaries, i)
    summary_writer.flush()

Run  `tensorboard --logdir=./logs` in bash

This is what you can see in your browser **(not available in Coursera Notebooks)**
<img src="https://github.com/hse-aml/intro-to-dl/blob/master/week2/v2/images/TensorBoard.jpg?raw=1" style="width:70%">

**If you're running on Google Colab you can still run TensorBoard!**

In [22]:
# !!! RUN THIS CELL ONLY ON GOOGLE COLAB !!!
! wget https://raw.githubusercontent.com/hse-aml/intro-to-dl/master/setup_google_colab.py -O setup_google_colab.py
import setup_google_colab

# run tensorboard in background
import os
os.system("tensorboard --logdir=./logs --host 0.0.0.0 --port 6006 &")

# expose port and show the link
setup_google_colab.expose_port_on_colab(6006)

--2020-07-07 14:36:47--  https://raw.githubusercontent.com/hse-aml/intro-to-dl/master/setup_google_colab.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3636 (3.6K) [text/plain]
Saving to: ‘setup_google_colab.py’

setup_google_colab. 100%[===================>]   3.55K  --.-KB/s    in 0s      

2020-07-07 14:36:48 (39.2 MB/s) - ‘setup_google_colab.py’ saved [3636/3636]

Can't get public url, retrying...
Open https://d336e0f0ff46.ngrok.io to access your 6006 port


In [23]:
s.close()

### Training a linear model

In [24]:
# generate model data
N = 1000
D = 3
x = np.random.random((N, D))
w = np.random.random((D, 1))
y = x @ w + np.random.randn(N, 1) * 0.20

print(x.shape, y.shape)
print(w.T)

(1000, 3) (1000, 1)
[[0.02825607 0.41690518 0.23000655]]


In [25]:
tf.reset_default_graph()

features = tf.placeholder(tf.float32, shape=(None, D))
target = tf.placeholder(tf.float32, shape=(None, 1))

weights = tf.get_variable("weights", shape=(D, 1), dtype=tf.float32)
predictions = features @ weights

loss = tf.reduce_mean((target - predictions) ** 2)

print(target.shape, predictions.shape, loss.shape)

(?, 1) (?, 1) ()


In [26]:
optimizer = tf.train.GradientDescentOptimizer(0.1)
step = optimizer.minimize(loss)

In [27]:
with tf.Session() as s:
    s.run(tf.global_variables_initializer())
    for i in range(300):
        _, curr_loss, curr_weights = s.run([step, loss, weights], 
                                           feed_dict={features: x, target: y})
        if i % 50 == 0:
            print(curr_loss)

3.6005518
0.036947723
0.03684505
0.036827404
0.03682437
0.03682385


In [28]:
# found weights
curr_weights.T

array([[0.03287547, 0.3950068 , 0.25796315]], dtype=float32)

In [29]:
# true weights
w.T

array([[0.02825607, 0.41690518, 0.23000655]])